// Code generated by ent, DO NOT EDIT.

package staff_role

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/golden-ocean/fiber-ocean/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v int64) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v int64) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldEQ(FieldUpdatedBy, v))
}

// StaffID applies equality check predicate on the "staff_id" field. It's identical to StaffIDEQ.
func StaffID(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldEQ(FieldStaffID, v))
}

// RoleID applies equality check predicate on the "role_id" field. It's identical to RoleIDEQ.
func RoleID(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldEQ(FieldRoleID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v int64) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v int64) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...int64) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...int64) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v int64) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v int64) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v int64) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v int64) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v int64) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v int64) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...int64) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...int64) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v int64) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v int64) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v int64) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v int64) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// StaffIDEQ applies the EQ predicate on the "staff_id" field.
func StaffIDEQ(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldEQ(FieldStaffID, v))
}

// StaffIDNEQ applies the NEQ predicate on the "staff_id" field.
func StaffIDNEQ(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldNEQ(FieldStaffID, v))
}

// StaffIDIn applies the In predicate on the "staff_id" field.
func StaffIDIn(vs ...string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldIn(FieldStaffID, vs...))
}

// StaffIDNotIn applies the NotIn predicate on the "staff_id" field.
func StaffIDNotIn(vs ...string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldNotIn(FieldStaffID, vs...))
}

// StaffIDGT applies the GT predicate on the "staff_id" field.
func StaffIDGT(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldGT(FieldStaffID, v))
}

// StaffIDGTE applies the GTE predicate on the "staff_id" field.
func StaffIDGTE(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldGTE(FieldStaffID, v))
}

// StaffIDLT applies the LT predicate on the "staff_id" field.
func StaffIDLT(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldLT(FieldStaffID, v))
}

// StaffIDLTE applies the LTE predicate on the "staff_id" field.
func StaffIDLTE(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldLTE(FieldStaffID, v))
}

// StaffIDContains applies the Contains predicate on the "staff_id" field.
func StaffIDContains(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldContains(FieldStaffID, v))
}

// StaffIDHasPrefix applies the HasPrefix predicate on the "staff_id" field.
func StaffIDHasPrefix(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldHasPrefix(FieldStaffID, v))
}

// StaffIDHasSuffix applies the HasSuffix predicate on the "staff_id" field.
func StaffIDHasSuffix(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldHasSuffix(FieldStaffID, v))
}

// StaffIDEqualFold applies the EqualFold predicate on the "staff_id" field.
func StaffIDEqualFold(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldEqualFold(FieldStaffID, v))
}

// StaffIDContainsFold applies the ContainsFold predicate on the "staff_id" field.
func StaffIDContainsFold(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldContainsFold(FieldStaffID, v))
}

// RoleIDEQ applies the EQ predicate on the "role_id" field.
func RoleIDEQ(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldEQ(FieldRoleID, v))
}

// RoleIDNEQ applies the NEQ predicate on the "role_id" field.
func RoleIDNEQ(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldNEQ(FieldRoleID, v))
}

// RoleIDIn applies the In predicate on the "role_id" field.
func RoleIDIn(vs ...string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldIn(FieldRoleID, vs...))
}

// RoleIDNotIn applies the NotIn predicate on the "role_id" field.
func RoleIDNotIn(vs ...string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldNotIn(FieldRoleID, vs...))
}

// RoleIDGT applies the GT predicate on the "role_id" field.
func RoleIDGT(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldGT(FieldRoleID, v))
}

// RoleIDGTE applies the GTE predicate on the "role_id" field.
func RoleIDGTE(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldGTE(FieldRoleID, v))
}

// RoleIDLT applies the LT predicate on the "role_id" field.
func RoleIDLT(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldLT(FieldRoleID, v))
}

// RoleIDLTE applies the LTE predicate on the "role_id" field.
func RoleIDLTE(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldLTE(FieldRoleID, v))
}

// RoleIDContains applies the Contains predicate on the "role_id" field.
func RoleIDContains(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldContains(FieldRoleID, v))
}

// RoleIDHasPrefix applies the HasPrefix predicate on the "role_id" field.
func RoleIDHasPrefix(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldHasPrefix(FieldRoleID, v))
}

// RoleIDHasSuffix applies the HasSuffix predicate on the "role_id" field.
func RoleIDHasSuffix(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldHasSuffix(FieldRoleID, v))
}

// RoleIDEqualFold applies the EqualFold predicate on the "role_id" field.
func RoleIDEqualFold(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldEqualFold(FieldRoleID, v))
}

// RoleIDContainsFold applies the ContainsFold predicate on the "role_id" field.
func RoleIDContainsFold(v string) predicate.Staff_Role {
	return predicate.Staff_Role(sql.FieldContainsFold(FieldRoleID, v))
}

// HasStaffs applies the HasEdge predicate on the "staffs" edge.
func HasStaffs() predicate.Staff_Role {
	return predicate.Staff_Role(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, StaffsTable, StaffsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStaffsWith applies the HasEdge predicate on the "staffs" edge with a given conditions (other predicates).
func HasStaffsWith(preds ...predicate.Staff) predicate.Staff_Role {
	return predicate.Staff_Role(func(s *sql.Selector) {
		step := newStaffsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRoles applies the HasEdge predicate on the "roles" edge.
func HasRoles() predicate.Staff_Role {
	return predicate.Staff_Role(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RolesTable, RolesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRolesWith applies the HasEdge predicate on the "roles" edge with a given conditions (other predicates).
func HasRolesWith(preds ...predicate.Role) predicate.Staff_Role {
	return predicate.Staff_Role(func(s *sql.Selector) {
		step := newRolesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Staff_Role) predicate.Staff_Role {
	return predicate.Staff_Role(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Staff_Role) predicate.Staff_Role {
	return predicate.Staff_Role(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Staff_Role) predicate.Staff_Role {
	return predicate.Staff_Role(sql.NotPredicates(p))
}
