// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"github.com/golden-ocean/fiber-ocean/ent/dictionary"
	"github.com/golden-ocean/fiber-ocean/ent/dictionary_item"
	"github.com/golden-ocean/fiber-ocean/ent/menu"
	"github.com/golden-ocean/fiber-ocean/ent/organization"
	"github.com/golden-ocean/fiber-ocean/ent/position"
	"github.com/golden-ocean/fiber-ocean/ent/role"
	"github.com/golden-ocean/fiber-ocean/ent/role_menu"
	"github.com/golden-ocean/fiber-ocean/ent/role_organization"
	"github.com/golden-ocean/fiber-ocean/ent/schema"
	"github.com/golden-ocean/fiber-ocean/ent/staff"
	"github.com/golden-ocean/fiber-ocean/ent/staff_position"
	"github.com/golden-ocean/fiber-ocean/ent/staff_role"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	dictionaryMixin := schema.Dictionary{}.Mixin()
	dictionaryMixinHooks0 := dictionaryMixin[0].Hooks()
	dictionary.Hooks[0] = dictionaryMixinHooks0[0]
	dictionary.Hooks[1] = dictionaryMixinHooks0[1]
	dictionaryMixinFields0 := dictionaryMixin[0].Fields()
	_ = dictionaryMixinFields0
	dictionaryMixinFields1 := dictionaryMixin[1].Fields()
	_ = dictionaryMixinFields1
	dictionaryFields := schema.Dictionary{}.Fields()
	_ = dictionaryFields
	// dictionaryDescCreatedAt is the schema descriptor for created_at field.
	dictionaryDescCreatedAt := dictionaryMixinFields0[1].Descriptor()
	// dictionary.DefaultCreatedAt holds the default value on creation for the created_at field.
	dictionary.DefaultCreatedAt = dictionaryDescCreatedAt.Default.(func() int64)
	// dictionaryDescUpdatedAt is the schema descriptor for updated_at field.
	dictionaryDescUpdatedAt := dictionaryMixinFields0[2].Descriptor()
	// dictionary.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	dictionary.DefaultUpdatedAt = dictionaryDescUpdatedAt.Default.(func() int64)
	// dictionaryDescStatus is the schema descriptor for status field.
	dictionaryDescStatus := dictionaryMixinFields1[0].Descriptor()
	// dictionary.DefaultStatus holds the default value on creation for the status field.
	dictionary.DefaultStatus = dictionaryDescStatus.Default.(string)
	// dictionaryDescSort is the schema descriptor for sort field.
	dictionaryDescSort := dictionaryMixinFields1[1].Descriptor()
	// dictionary.DefaultSort holds the default value on creation for the sort field.
	dictionary.DefaultSort = dictionaryDescSort.Default.(int32)
	// dictionaryDescName is the schema descriptor for name field.
	dictionaryDescName := dictionaryFields[0].Descriptor()
	// dictionary.NameValidator is a validator for the "name" field. It is called by the builders before save.
	dictionary.NameValidator = func() func(string) error {
		validators := dictionaryDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// dictionaryDescCode is the schema descriptor for code field.
	dictionaryDescCode := dictionaryFields[1].Descriptor()
	// dictionary.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	dictionary.CodeValidator = func() func(string) error {
		validators := dictionaryDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// dictionaryDescID is the schema descriptor for id field.
	dictionaryDescID := dictionaryMixinFields0[0].Descriptor()
	// dictionary.IDValidator is a validator for the "id" field. It is called by the builders before save.
	dictionary.IDValidator = dictionaryDescID.Validators[0].(func(string) error)
	dictionary_itemMixin := schema.Dictionary_Item{}.Mixin()
	dictionary_itemMixinHooks0 := dictionary_itemMixin[0].Hooks()
	dictionary_item.Hooks[0] = dictionary_itemMixinHooks0[0]
	dictionary_item.Hooks[1] = dictionary_itemMixinHooks0[1]
	dictionary_itemMixinFields0 := dictionary_itemMixin[0].Fields()
	_ = dictionary_itemMixinFields0
	dictionary_itemMixinFields1 := dictionary_itemMixin[1].Fields()
	_ = dictionary_itemMixinFields1
	dictionary_itemFields := schema.Dictionary_Item{}.Fields()
	_ = dictionary_itemFields
	// dictionary_itemDescCreatedAt is the schema descriptor for created_at field.
	dictionary_itemDescCreatedAt := dictionary_itemMixinFields0[1].Descriptor()
	// dictionary_item.DefaultCreatedAt holds the default value on creation for the created_at field.
	dictionary_item.DefaultCreatedAt = dictionary_itemDescCreatedAt.Default.(func() int64)
	// dictionary_itemDescUpdatedAt is the schema descriptor for updated_at field.
	dictionary_itemDescUpdatedAt := dictionary_itemMixinFields0[2].Descriptor()
	// dictionary_item.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	dictionary_item.DefaultUpdatedAt = dictionary_itemDescUpdatedAt.Default.(func() int64)
	// dictionary_itemDescStatus is the schema descriptor for status field.
	dictionary_itemDescStatus := dictionary_itemMixinFields1[0].Descriptor()
	// dictionary_item.DefaultStatus holds the default value on creation for the status field.
	dictionary_item.DefaultStatus = dictionary_itemDescStatus.Default.(string)
	// dictionary_itemDescSort is the schema descriptor for sort field.
	dictionary_itemDescSort := dictionary_itemMixinFields1[1].Descriptor()
	// dictionary_item.DefaultSort holds the default value on creation for the sort field.
	dictionary_item.DefaultSort = dictionary_itemDescSort.Default.(int32)
	// dictionary_itemDescLabel is the schema descriptor for label field.
	dictionary_itemDescLabel := dictionary_itemFields[0].Descriptor()
	// dictionary_item.LabelValidator is a validator for the "label" field. It is called by the builders before save.
	dictionary_item.LabelValidator = func() func(string) error {
		validators := dictionary_itemDescLabel.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(label string) error {
			for _, fn := range fns {
				if err := fn(label); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// dictionary_itemDescValue is the schema descriptor for value field.
	dictionary_itemDescValue := dictionary_itemFields[1].Descriptor()
	// dictionary_item.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	dictionary_item.ValueValidator = func() func(string) error {
		validators := dictionary_itemDescValue.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(value string) error {
			for _, fn := range fns {
				if err := fn(value); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// dictionary_itemDescColor is the schema descriptor for color field.
	dictionary_itemDescColor := dictionary_itemFields[2].Descriptor()
	// dictionary_item.ColorValidator is a validator for the "color" field. It is called by the builders before save.
	dictionary_item.ColorValidator = func() func(string) error {
		validators := dictionary_itemDescColor.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(color string) error {
			for _, fn := range fns {
				if err := fn(color); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// dictionary_itemDescDictionaryID is the schema descriptor for dictionary_id field.
	dictionary_itemDescDictionaryID := dictionary_itemFields[3].Descriptor()
	// dictionary_item.DictionaryIDValidator is a validator for the "dictionary_id" field. It is called by the builders before save.
	dictionary_item.DictionaryIDValidator = dictionary_itemDescDictionaryID.Validators[0].(func(string) error)
	// dictionary_itemDescID is the schema descriptor for id field.
	dictionary_itemDescID := dictionary_itemMixinFields0[0].Descriptor()
	// dictionary_item.IDValidator is a validator for the "id" field. It is called by the builders before save.
	dictionary_item.IDValidator = dictionary_itemDescID.Validators[0].(func(string) error)
	menuMixin := schema.Menu{}.Mixin()
	menuMixinHooks0 := menuMixin[0].Hooks()
	menu.Hooks[0] = menuMixinHooks0[0]
	menu.Hooks[1] = menuMixinHooks0[1]
	menuMixinFields0 := menuMixin[0].Fields()
	_ = menuMixinFields0
	menuMixinFields1 := menuMixin[1].Fields()
	_ = menuMixinFields1
	menuFields := schema.Menu{}.Fields()
	_ = menuFields
	// menuDescCreatedAt is the schema descriptor for created_at field.
	menuDescCreatedAt := menuMixinFields0[1].Descriptor()
	// menu.DefaultCreatedAt holds the default value on creation for the created_at field.
	menu.DefaultCreatedAt = menuDescCreatedAt.Default.(func() int64)
	// menuDescUpdatedAt is the schema descriptor for updated_at field.
	menuDescUpdatedAt := menuMixinFields0[2].Descriptor()
	// menu.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	menu.DefaultUpdatedAt = menuDescUpdatedAt.Default.(func() int64)
	// menuDescStatus is the schema descriptor for status field.
	menuDescStatus := menuMixinFields1[0].Descriptor()
	// menu.DefaultStatus holds the default value on creation for the status field.
	menu.DefaultStatus = menuDescStatus.Default.(string)
	// menuDescSort is the schema descriptor for sort field.
	menuDescSort := menuMixinFields1[1].Descriptor()
	// menu.DefaultSort holds the default value on creation for the sort field.
	menu.DefaultSort = menuDescSort.Default.(int32)
	// menuDescName is the schema descriptor for name field.
	menuDescName := menuFields[0].Descriptor()
	// menu.NameValidator is a validator for the "name" field. It is called by the builders before save.
	menu.NameValidator = func() func(string) error {
		validators := menuDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// menuDescVisible is the schema descriptor for visible field.
	menuDescVisible := menuFields[8].Descriptor()
	// menu.DefaultVisible holds the default value on creation for the visible field.
	menu.DefaultVisible = menuDescVisible.Default.(string)
	// menuDescID is the schema descriptor for id field.
	menuDescID := menuMixinFields0[0].Descriptor()
	// menu.IDValidator is a validator for the "id" field. It is called by the builders before save.
	menu.IDValidator = menuDescID.Validators[0].(func(string) error)
	organizationMixin := schema.Organization{}.Mixin()
	organizationMixinHooks0 := organizationMixin[0].Hooks()
	organization.Hooks[0] = organizationMixinHooks0[0]
	organization.Hooks[1] = organizationMixinHooks0[1]
	organizationMixinFields0 := organizationMixin[0].Fields()
	_ = organizationMixinFields0
	organizationMixinFields1 := organizationMixin[1].Fields()
	_ = organizationMixinFields1
	organizationFields := schema.Organization{}.Fields()
	_ = organizationFields
	// organizationDescCreatedAt is the schema descriptor for created_at field.
	organizationDescCreatedAt := organizationMixinFields0[1].Descriptor()
	// organization.DefaultCreatedAt holds the default value on creation for the created_at field.
	organization.DefaultCreatedAt = organizationDescCreatedAt.Default.(func() int64)
	// organizationDescUpdatedAt is the schema descriptor for updated_at field.
	organizationDescUpdatedAt := organizationMixinFields0[2].Descriptor()
	// organization.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	organization.DefaultUpdatedAt = organizationDescUpdatedAt.Default.(func() int64)
	// organizationDescStatus is the schema descriptor for status field.
	organizationDescStatus := organizationMixinFields1[0].Descriptor()
	// organization.DefaultStatus holds the default value on creation for the status field.
	organization.DefaultStatus = organizationDescStatus.Default.(string)
	// organizationDescSort is the schema descriptor for sort field.
	organizationDescSort := organizationMixinFields1[1].Descriptor()
	// organization.DefaultSort holds the default value on creation for the sort field.
	organization.DefaultSort = organizationDescSort.Default.(int32)
	// organizationDescName is the schema descriptor for name field.
	organizationDescName := organizationFields[0].Descriptor()
	// organization.NameValidator is a validator for the "name" field. It is called by the builders before save.
	organization.NameValidator = func() func(string) error {
		validators := organizationDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// organizationDescCode is the schema descriptor for code field.
	organizationDescCode := organizationFields[1].Descriptor()
	// organization.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	organization.CodeValidator = func() func(string) error {
		validators := organizationDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// organizationDescID is the schema descriptor for id field.
	organizationDescID := organizationMixinFields0[0].Descriptor()
	// organization.IDValidator is a validator for the "id" field. It is called by the builders before save.
	organization.IDValidator = organizationDescID.Validators[0].(func(string) error)
	positionMixin := schema.Position{}.Mixin()
	positionMixinHooks0 := positionMixin[0].Hooks()
	position.Hooks[0] = positionMixinHooks0[0]
	position.Hooks[1] = positionMixinHooks0[1]
	positionMixinFields0 := positionMixin[0].Fields()
	_ = positionMixinFields0
	positionMixinFields1 := positionMixin[1].Fields()
	_ = positionMixinFields1
	positionFields := schema.Position{}.Fields()
	_ = positionFields
	// positionDescCreatedAt is the schema descriptor for created_at field.
	positionDescCreatedAt := positionMixinFields0[1].Descriptor()
	// position.DefaultCreatedAt holds the default value on creation for the created_at field.
	position.DefaultCreatedAt = positionDescCreatedAt.Default.(func() int64)
	// positionDescUpdatedAt is the schema descriptor for updated_at field.
	positionDescUpdatedAt := positionMixinFields0[2].Descriptor()
	// position.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	position.DefaultUpdatedAt = positionDescUpdatedAt.Default.(func() int64)
	// positionDescStatus is the schema descriptor for status field.
	positionDescStatus := positionMixinFields1[0].Descriptor()
	// position.DefaultStatus holds the default value on creation for the status field.
	position.DefaultStatus = positionDescStatus.Default.(string)
	// positionDescSort is the schema descriptor for sort field.
	positionDescSort := positionMixinFields1[1].Descriptor()
	// position.DefaultSort holds the default value on creation for the sort field.
	position.DefaultSort = positionDescSort.Default.(int32)
	// positionDescName is the schema descriptor for name field.
	positionDescName := positionFields[0].Descriptor()
	// position.NameValidator is a validator for the "name" field. It is called by the builders before save.
	position.NameValidator = func() func(string) error {
		validators := positionDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// positionDescCode is the schema descriptor for code field.
	positionDescCode := positionFields[1].Descriptor()
	// position.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	position.CodeValidator = func() func(string) error {
		validators := positionDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// positionDescID is the schema descriptor for id field.
	positionDescID := positionMixinFields0[0].Descriptor()
	// position.IDValidator is a validator for the "id" field. It is called by the builders before save.
	position.IDValidator = positionDescID.Validators[0].(func(string) error)
	roleMixin := schema.Role{}.Mixin()
	roleMixinHooks0 := roleMixin[0].Hooks()
	role.Hooks[0] = roleMixinHooks0[0]
	role.Hooks[1] = roleMixinHooks0[1]
	roleMixinFields0 := roleMixin[0].Fields()
	_ = roleMixinFields0
	roleMixinFields1 := roleMixin[1].Fields()
	_ = roleMixinFields1
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleMixinFields0[1].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() int64)
	// roleDescUpdatedAt is the schema descriptor for updated_at field.
	roleDescUpdatedAt := roleMixinFields0[2].Descriptor()
	// role.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	role.DefaultUpdatedAt = roleDescUpdatedAt.Default.(func() int64)
	// roleDescStatus is the schema descriptor for status field.
	roleDescStatus := roleMixinFields1[0].Descriptor()
	// role.DefaultStatus holds the default value on creation for the status field.
	role.DefaultStatus = roleDescStatus.Default.(string)
	// roleDescSort is the schema descriptor for sort field.
	roleDescSort := roleMixinFields1[1].Descriptor()
	// role.DefaultSort holds the default value on creation for the sort field.
	role.DefaultSort = roleDescSort.Default.(int32)
	// roleDescName is the schema descriptor for name field.
	roleDescName := roleFields[0].Descriptor()
	// role.NameValidator is a validator for the "name" field. It is called by the builders before save.
	role.NameValidator = func() func(string) error {
		validators := roleDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// roleDescCode is the schema descriptor for code field.
	roleDescCode := roleFields[1].Descriptor()
	// role.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	role.CodeValidator = func() func(string) error {
		validators := roleDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// roleDescID is the schema descriptor for id field.
	roleDescID := roleMixinFields0[0].Descriptor()
	// role.IDValidator is a validator for the "id" field. It is called by the builders before save.
	role.IDValidator = roleDescID.Validators[0].(func(string) error)
	role_menuMixin := schema.Role_Menu{}.Mixin()
	role_menuMixinHooks0 := role_menuMixin[0].Hooks()
	role_menu.Hooks[0] = role_menuMixinHooks0[0]
	role_menu.Hooks[1] = role_menuMixinHooks0[1]
	role_menuMixinFields0 := role_menuMixin[0].Fields()
	_ = role_menuMixinFields0
	role_menuFields := schema.Role_Menu{}.Fields()
	_ = role_menuFields
	// role_menuDescCreatedAt is the schema descriptor for created_at field.
	role_menuDescCreatedAt := role_menuMixinFields0[1].Descriptor()
	// role_menu.DefaultCreatedAt holds the default value on creation for the created_at field.
	role_menu.DefaultCreatedAt = role_menuDescCreatedAt.Default.(func() int64)
	// role_menuDescUpdatedAt is the schema descriptor for updated_at field.
	role_menuDescUpdatedAt := role_menuMixinFields0[2].Descriptor()
	// role_menu.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	role_menu.DefaultUpdatedAt = role_menuDescUpdatedAt.Default.(func() int64)
	// role_menuDescRoleID is the schema descriptor for role_id field.
	role_menuDescRoleID := role_menuFields[0].Descriptor()
	// role_menu.RoleIDValidator is a validator for the "role_id" field. It is called by the builders before save.
	role_menu.RoleIDValidator = role_menuDescRoleID.Validators[0].(func(string) error)
	// role_menuDescMenuID is the schema descriptor for menu_id field.
	role_menuDescMenuID := role_menuFields[1].Descriptor()
	// role_menu.MenuIDValidator is a validator for the "menu_id" field. It is called by the builders before save.
	role_menu.MenuIDValidator = role_menuDescMenuID.Validators[0].(func(string) error)
	// role_menuDescID is the schema descriptor for id field.
	role_menuDescID := role_menuMixinFields0[0].Descriptor()
	// role_menu.IDValidator is a validator for the "id" field. It is called by the builders before save.
	role_menu.IDValidator = role_menuDescID.Validators[0].(func(string) error)
	role_organizationMixin := schema.Role_Organization{}.Mixin()
	role_organizationMixinHooks0 := role_organizationMixin[0].Hooks()
	role_organization.Hooks[0] = role_organizationMixinHooks0[0]
	role_organization.Hooks[1] = role_organizationMixinHooks0[1]
	role_organizationMixinFields0 := role_organizationMixin[0].Fields()
	_ = role_organizationMixinFields0
	role_organizationFields := schema.Role_Organization{}.Fields()
	_ = role_organizationFields
	// role_organizationDescCreatedAt is the schema descriptor for created_at field.
	role_organizationDescCreatedAt := role_organizationMixinFields0[1].Descriptor()
	// role_organization.DefaultCreatedAt holds the default value on creation for the created_at field.
	role_organization.DefaultCreatedAt = role_organizationDescCreatedAt.Default.(func() int64)
	// role_organizationDescUpdatedAt is the schema descriptor for updated_at field.
	role_organizationDescUpdatedAt := role_organizationMixinFields0[2].Descriptor()
	// role_organization.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	role_organization.DefaultUpdatedAt = role_organizationDescUpdatedAt.Default.(func() int64)
	// role_organizationDescRoleID is the schema descriptor for role_id field.
	role_organizationDescRoleID := role_organizationFields[0].Descriptor()
	// role_organization.RoleIDValidator is a validator for the "role_id" field. It is called by the builders before save.
	role_organization.RoleIDValidator = role_organizationDescRoleID.Validators[0].(func(string) error)
	// role_organizationDescOrganizationID is the schema descriptor for organization_id field.
	role_organizationDescOrganizationID := role_organizationFields[1].Descriptor()
	// role_organization.OrganizationIDValidator is a validator for the "organization_id" field. It is called by the builders before save.
	role_organization.OrganizationIDValidator = role_organizationDescOrganizationID.Validators[0].(func(string) error)
	// role_organizationDescID is the schema descriptor for id field.
	role_organizationDescID := role_organizationMixinFields0[0].Descriptor()
	// role_organization.IDValidator is a validator for the "id" field. It is called by the builders before save.
	role_organization.IDValidator = role_organizationDescID.Validators[0].(func(string) error)
	staffMixin := schema.Staff{}.Mixin()
	staffMixinHooks0 := staffMixin[0].Hooks()
	staff.Hooks[0] = staffMixinHooks0[0]
	staff.Hooks[1] = staffMixinHooks0[1]
	staffMixinFields0 := staffMixin[0].Fields()
	_ = staffMixinFields0
	staffMixinFields1 := staffMixin[1].Fields()
	_ = staffMixinFields1
	staffFields := schema.Staff{}.Fields()
	_ = staffFields
	// staffDescCreatedAt is the schema descriptor for created_at field.
	staffDescCreatedAt := staffMixinFields0[1].Descriptor()
	// staff.DefaultCreatedAt holds the default value on creation for the created_at field.
	staff.DefaultCreatedAt = staffDescCreatedAt.Default.(func() int64)
	// staffDescUpdatedAt is the schema descriptor for updated_at field.
	staffDescUpdatedAt := staffMixinFields0[2].Descriptor()
	// staff.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	staff.DefaultUpdatedAt = staffDescUpdatedAt.Default.(func() int64)
	// staffDescStatus is the schema descriptor for status field.
	staffDescStatus := staffMixinFields1[0].Descriptor()
	// staff.DefaultStatus holds the default value on creation for the status field.
	staff.DefaultStatus = staffDescStatus.Default.(string)
	// staffDescSort is the schema descriptor for sort field.
	staffDescSort := staffMixinFields1[1].Descriptor()
	// staff.DefaultSort holds the default value on creation for the sort field.
	staff.DefaultSort = staffDescSort.Default.(int32)
	// staffDescUsername is the schema descriptor for username field.
	staffDescUsername := staffFields[0].Descriptor()
	// staff.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	staff.UsernameValidator = staffDescUsername.Validators[0].(func(string) error)
	// staffDescPassword is the schema descriptor for password field.
	staffDescPassword := staffFields[1].Descriptor()
	// staff.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	staff.PasswordValidator = staffDescPassword.Validators[0].(func(string) error)
	// staffDescName is the schema descriptor for name field.
	staffDescName := staffFields[2].Descriptor()
	// staff.NameValidator is a validator for the "name" field. It is called by the builders before save.
	staff.NameValidator = staffDescName.Validators[0].(func(string) error)
	// staffDescMobile is the schema descriptor for mobile field.
	staffDescMobile := staffFields[5].Descriptor()
	// staff.MobileValidator is a validator for the "mobile" field. It is called by the builders before save.
	staff.MobileValidator = staffDescMobile.Validators[0].(func(string) error)
	// staffDescEmail is the schema descriptor for email field.
	staffDescEmail := staffFields[6].Descriptor()
	// staff.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	staff.EmailValidator = staffDescEmail.Validators[0].(func(string) error)
	// staffDescID is the schema descriptor for id field.
	staffDescID := staffMixinFields0[0].Descriptor()
	// staff.IDValidator is a validator for the "id" field. It is called by the builders before save.
	staff.IDValidator = staffDescID.Validators[0].(func(string) error)
	staff_positionMixin := schema.Staff_Position{}.Mixin()
	staff_positionMixinHooks0 := staff_positionMixin[0].Hooks()
	staff_position.Hooks[0] = staff_positionMixinHooks0[0]
	staff_position.Hooks[1] = staff_positionMixinHooks0[1]
	staff_positionMixinFields0 := staff_positionMixin[0].Fields()
	_ = staff_positionMixinFields0
	staff_positionFields := schema.Staff_Position{}.Fields()
	_ = staff_positionFields
	// staff_positionDescCreatedAt is the schema descriptor for created_at field.
	staff_positionDescCreatedAt := staff_positionMixinFields0[1].Descriptor()
	// staff_position.DefaultCreatedAt holds the default value on creation for the created_at field.
	staff_position.DefaultCreatedAt = staff_positionDescCreatedAt.Default.(func() int64)
	// staff_positionDescUpdatedAt is the schema descriptor for updated_at field.
	staff_positionDescUpdatedAt := staff_positionMixinFields0[2].Descriptor()
	// staff_position.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	staff_position.DefaultUpdatedAt = staff_positionDescUpdatedAt.Default.(func() int64)
	// staff_positionDescStaffID is the schema descriptor for staff_id field.
	staff_positionDescStaffID := staff_positionFields[0].Descriptor()
	// staff_position.StaffIDValidator is a validator for the "staff_id" field. It is called by the builders before save.
	staff_position.StaffIDValidator = staff_positionDescStaffID.Validators[0].(func(string) error)
	// staff_positionDescPositionID is the schema descriptor for position_id field.
	staff_positionDescPositionID := staff_positionFields[1].Descriptor()
	// staff_position.PositionIDValidator is a validator for the "position_id" field. It is called by the builders before save.
	staff_position.PositionIDValidator = staff_positionDescPositionID.Validators[0].(func(string) error)
	// staff_positionDescID is the schema descriptor for id field.
	staff_positionDescID := staff_positionMixinFields0[0].Descriptor()
	// staff_position.IDValidator is a validator for the "id" field. It is called by the builders before save.
	staff_position.IDValidator = staff_positionDescID.Validators[0].(func(string) error)
	staff_roleMixin := schema.Staff_Role{}.Mixin()
	staff_roleMixinHooks0 := staff_roleMixin[0].Hooks()
	staff_role.Hooks[0] = staff_roleMixinHooks0[0]
	staff_role.Hooks[1] = staff_roleMixinHooks0[1]
	staff_roleMixinFields0 := staff_roleMixin[0].Fields()
	_ = staff_roleMixinFields0
	staff_roleFields := schema.Staff_Role{}.Fields()
	_ = staff_roleFields
	// staff_roleDescCreatedAt is the schema descriptor for created_at field.
	staff_roleDescCreatedAt := staff_roleMixinFields0[1].Descriptor()
	// staff_role.DefaultCreatedAt holds the default value on creation for the created_at field.
	staff_role.DefaultCreatedAt = staff_roleDescCreatedAt.Default.(func() int64)
	// staff_roleDescUpdatedAt is the schema descriptor for updated_at field.
	staff_roleDescUpdatedAt := staff_roleMixinFields0[2].Descriptor()
	// staff_role.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	staff_role.DefaultUpdatedAt = staff_roleDescUpdatedAt.Default.(func() int64)
	// staff_roleDescStaffID is the schema descriptor for staff_id field.
	staff_roleDescStaffID := staff_roleFields[0].Descriptor()
	// staff_role.StaffIDValidator is a validator for the "staff_id" field. It is called by the builders before save.
	staff_role.StaffIDValidator = staff_roleDescStaffID.Validators[0].(func(string) error)
	// staff_roleDescRoleID is the schema descriptor for role_id field.
	staff_roleDescRoleID := staff_roleFields[1].Descriptor()
	// staff_role.RoleIDValidator is a validator for the "role_id" field. It is called by the builders before save.
	staff_role.RoleIDValidator = staff_roleDescRoleID.Validators[0].(func(string) error)
	// staff_roleDescID is the schema descriptor for id field.
	staff_roleDescID := staff_roleMixinFields0[0].Descriptor()
	// staff_role.IDValidator is a validator for the "id" field. It is called by the builders before save.
	staff_role.IDValidator = staff_roleDescID.Validators[0].(func(string) error)
}

const (
	Version = "v0.13.1"                                         // Version of ent codegen.
	Sum     = "h1:uD8QwN1h6SNphdCCzmkMN3feSUzNnVvV/WIkHKMbzOE=" // Sum of ent codegen.
)
