// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/golden-ocean/fiber-ocean/ent/dictionary"
	"github.com/golden-ocean/fiber-ocean/ent/dictionary_item"
	"github.com/golden-ocean/fiber-ocean/ent/predicate"
)

// DictionaryItemQuery is the builder for querying Dictionary_Item entities.
type DictionaryItemQuery struct {
	config
	ctx            *QueryContext
	order          []dictionary_item.OrderOption
	inters         []Interceptor
	predicates     []predicate.Dictionary_Item
	withDictionary *DictionaryQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DictionaryItemQuery builder.
func (diq *DictionaryItemQuery) Where(ps ...predicate.Dictionary_Item) *DictionaryItemQuery {
	diq.predicates = append(diq.predicates, ps...)
	return diq
}

// Limit the number of records to be returned by this query.
func (diq *DictionaryItemQuery) Limit(limit int) *DictionaryItemQuery {
	diq.ctx.Limit = &limit
	return diq
}

// Offset to start from.
func (diq *DictionaryItemQuery) Offset(offset int) *DictionaryItemQuery {
	diq.ctx.Offset = &offset
	return diq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (diq *DictionaryItemQuery) Unique(unique bool) *DictionaryItemQuery {
	diq.ctx.Unique = &unique
	return diq
}

// Order specifies how the records should be ordered.
func (diq *DictionaryItemQuery) Order(o ...dictionary_item.OrderOption) *DictionaryItemQuery {
	diq.order = append(diq.order, o...)
	return diq
}

// QueryDictionary chains the current query on the "dictionary" edge.
func (diq *DictionaryItemQuery) QueryDictionary() *DictionaryQuery {
	query := (&DictionaryClient{config: diq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := diq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := diq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(dictionary_item.Table, dictionary_item.FieldID, selector),
			sqlgraph.To(dictionary.Table, dictionary.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, dictionary_item.DictionaryTable, dictionary_item.DictionaryColumn),
		)
		fromU = sqlgraph.SetNeighbors(diq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Dictionary_Item entity from the query.
// Returns a *NotFoundError when no Dictionary_Item was found.
func (diq *DictionaryItemQuery) First(ctx context.Context) (*Dictionary_Item, error) {
	nodes, err := diq.Limit(1).All(setContextOp(ctx, diq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{dictionary_item.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (diq *DictionaryItemQuery) FirstX(ctx context.Context) *Dictionary_Item {
	node, err := diq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Dictionary_Item ID from the query.
// Returns a *NotFoundError when no Dictionary_Item ID was found.
func (diq *DictionaryItemQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = diq.Limit(1).IDs(setContextOp(ctx, diq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{dictionary_item.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (diq *DictionaryItemQuery) FirstIDX(ctx context.Context) string {
	id, err := diq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Dictionary_Item entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Dictionary_Item entity is found.
// Returns a *NotFoundError when no Dictionary_Item entities are found.
func (diq *DictionaryItemQuery) Only(ctx context.Context) (*Dictionary_Item, error) {
	nodes, err := diq.Limit(2).All(setContextOp(ctx, diq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{dictionary_item.Label}
	default:
		return nil, &NotSingularError{dictionary_item.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (diq *DictionaryItemQuery) OnlyX(ctx context.Context) *Dictionary_Item {
	node, err := diq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Dictionary_Item ID in the query.
// Returns a *NotSingularError when more than one Dictionary_Item ID is found.
// Returns a *NotFoundError when no entities are found.
func (diq *DictionaryItemQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = diq.Limit(2).IDs(setContextOp(ctx, diq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{dictionary_item.Label}
	default:
		err = &NotSingularError{dictionary_item.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (diq *DictionaryItemQuery) OnlyIDX(ctx context.Context) string {
	id, err := diq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Dictionary_Items.
func (diq *DictionaryItemQuery) All(ctx context.Context) ([]*Dictionary_Item, error) {
	ctx = setContextOp(ctx, diq.ctx, "All")
	if err := diq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Dictionary_Item, *DictionaryItemQuery]()
	return withInterceptors[[]*Dictionary_Item](ctx, diq, qr, diq.inters)
}

// AllX is like All, but panics if an error occurs.
func (diq *DictionaryItemQuery) AllX(ctx context.Context) []*Dictionary_Item {
	nodes, err := diq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Dictionary_Item IDs.
func (diq *DictionaryItemQuery) IDs(ctx context.Context) (ids []string, err error) {
	if diq.ctx.Unique == nil && diq.path != nil {
		diq.Unique(true)
	}
	ctx = setContextOp(ctx, diq.ctx, "IDs")
	if err = diq.Select(dictionary_item.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (diq *DictionaryItemQuery) IDsX(ctx context.Context) []string {
	ids, err := diq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (diq *DictionaryItemQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, diq.ctx, "Count")
	if err := diq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, diq, querierCount[*DictionaryItemQuery](), diq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (diq *DictionaryItemQuery) CountX(ctx context.Context) int {
	count, err := diq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (diq *DictionaryItemQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, diq.ctx, "Exist")
	switch _, err := diq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (diq *DictionaryItemQuery) ExistX(ctx context.Context) bool {
	exist, err := diq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DictionaryItemQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (diq *DictionaryItemQuery) Clone() *DictionaryItemQuery {
	if diq == nil {
		return nil
	}
	return &DictionaryItemQuery{
		config:         diq.config,
		ctx:            diq.ctx.Clone(),
		order:          append([]dictionary_item.OrderOption{}, diq.order...),
		inters:         append([]Interceptor{}, diq.inters...),
		predicates:     append([]predicate.Dictionary_Item{}, diq.predicates...),
		withDictionary: diq.withDictionary.Clone(),
		// clone intermediate query.
		sql:  diq.sql.Clone(),
		path: diq.path,
	}
}

// WithDictionary tells the query-builder to eager-load the nodes that are connected to
// the "dictionary" edge. The optional arguments are used to configure the query builder of the edge.
func (diq *DictionaryItemQuery) WithDictionary(opts ...func(*DictionaryQuery)) *DictionaryItemQuery {
	query := (&DictionaryClient{config: diq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	diq.withDictionary = query
	return diq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt int64 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DictionaryItem.Query().
//		GroupBy(dictionary_item.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (diq *DictionaryItemQuery) GroupBy(field string, fields ...string) *DictionaryItemGroupBy {
	diq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DictionaryItemGroupBy{build: diq}
	grbuild.flds = &diq.ctx.Fields
	grbuild.label = dictionary_item.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt int64 `json:"created_at,omitempty"`
//	}
//
//	client.DictionaryItem.Query().
//		Select(dictionary_item.FieldCreatedAt).
//		Scan(ctx, &v)
func (diq *DictionaryItemQuery) Select(fields ...string) *DictionaryItemSelect {
	diq.ctx.Fields = append(diq.ctx.Fields, fields...)
	sbuild := &DictionaryItemSelect{DictionaryItemQuery: diq}
	sbuild.label = dictionary_item.Label
	sbuild.flds, sbuild.scan = &diq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DictionaryItemSelect configured with the given aggregations.
func (diq *DictionaryItemQuery) Aggregate(fns ...AggregateFunc) *DictionaryItemSelect {
	return diq.Select().Aggregate(fns...)
}

func (diq *DictionaryItemQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range diq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, diq); err != nil {
				return err
			}
		}
	}
	for _, f := range diq.ctx.Fields {
		if !dictionary_item.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if diq.path != nil {
		prev, err := diq.path(ctx)
		if err != nil {
			return err
		}
		diq.sql = prev
	}
	return nil
}

func (diq *DictionaryItemQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Dictionary_Item, error) {
	var (
		nodes       = []*Dictionary_Item{}
		_spec       = diq.querySpec()
		loadedTypes = [1]bool{
			diq.withDictionary != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Dictionary_Item).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Dictionary_Item{config: diq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, diq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := diq.withDictionary; query != nil {
		if err := diq.loadDictionary(ctx, query, nodes, nil,
			func(n *Dictionary_Item, e *Dictionary) { n.Edges.Dictionary = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (diq *DictionaryItemQuery) loadDictionary(ctx context.Context, query *DictionaryQuery, nodes []*Dictionary_Item, init func(*Dictionary_Item), assign func(*Dictionary_Item, *Dictionary)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Dictionary_Item)
	for i := range nodes {
		fk := nodes[i].DictionaryID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(dictionary.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "dictionary_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (diq *DictionaryItemQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := diq.querySpec()
	_spec.Node.Columns = diq.ctx.Fields
	if len(diq.ctx.Fields) > 0 {
		_spec.Unique = diq.ctx.Unique != nil && *diq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, diq.driver, _spec)
}

func (diq *DictionaryItemQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(dictionary_item.Table, dictionary_item.Columns, sqlgraph.NewFieldSpec(dictionary_item.FieldID, field.TypeString))
	_spec.From = diq.sql
	if unique := diq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if diq.path != nil {
		_spec.Unique = true
	}
	if fields := diq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dictionary_item.FieldID)
		for i := range fields {
			if fields[i] != dictionary_item.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if diq.withDictionary != nil {
			_spec.Node.AddColumnOnce(dictionary_item.FieldDictionaryID)
		}
	}
	if ps := diq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := diq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := diq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := diq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (diq *DictionaryItemQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(diq.driver.Dialect())
	t1 := builder.Table(dictionary_item.Table)
	columns := diq.ctx.Fields
	if len(columns) == 0 {
		columns = dictionary_item.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if diq.sql != nil {
		selector = diq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if diq.ctx.Unique != nil && *diq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range diq.predicates {
		p(selector)
	}
	for _, p := range diq.order {
		p(selector)
	}
	if offset := diq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := diq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DictionaryItemGroupBy is the group-by builder for Dictionary_Item entities.
type DictionaryItemGroupBy struct {
	selector
	build *DictionaryItemQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (digb *DictionaryItemGroupBy) Aggregate(fns ...AggregateFunc) *DictionaryItemGroupBy {
	digb.fns = append(digb.fns, fns...)
	return digb
}

// Scan applies the selector query and scans the result into the given value.
func (digb *DictionaryItemGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, digb.build.ctx, "GroupBy")
	if err := digb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DictionaryItemQuery, *DictionaryItemGroupBy](ctx, digb.build, digb, digb.build.inters, v)
}

func (digb *DictionaryItemGroupBy) sqlScan(ctx context.Context, root *DictionaryItemQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(digb.fns))
	for _, fn := range digb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*digb.flds)+len(digb.fns))
		for _, f := range *digb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*digb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := digb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DictionaryItemSelect is the builder for selecting fields of DictionaryItem entities.
type DictionaryItemSelect struct {
	*DictionaryItemQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (dis *DictionaryItemSelect) Aggregate(fns ...AggregateFunc) *DictionaryItemSelect {
	dis.fns = append(dis.fns, fns...)
	return dis
}

// Scan applies the selector query and scans the result into the given value.
func (dis *DictionaryItemSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dis.ctx, "Select")
	if err := dis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DictionaryItemQuery, *DictionaryItemSelect](ctx, dis.DictionaryItemQuery, dis, dis.inters, v)
}

func (dis *DictionaryItemSelect) sqlScan(ctx context.Context, root *DictionaryItemQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(dis.fns))
	for _, fn := range dis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*dis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
