// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/golden-ocean/fiber-ocean/ent/menu"
	"github.com/golden-ocean/fiber-ocean/ent/role"
	"github.com/golden-ocean/fiber-ocean/ent/role_menu"
)

// Role_Menu is the model entity for the Role_Menu schema.
type Role_Menu struct {
	config `json:"-"`
	// ID of the ent.
	// 主键
	ID string `json:"id,omitempty"`
	// 创建时间
	CreatedAt int64 `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt int64 `json:"updated_at,omitempty"`
	// 创建人员
	CreatedBy string `json:"created_by,omitempty"`
	// 更新人员
	UpdatedBy string `json:"updated_by,omitempty"`
	// 角色ID
	RoleID string `json:"role_id,omitempty"`
	// 菜单ID
	MenuID string `json:"menu_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the Role_MenuQuery when eager-loading is set.
	Edges        Role_MenuEdges `json:"-"`
	selectValues sql.SelectValues
}

// Role_MenuEdges holds the relations/edges for other nodes in the graph.
type Role_MenuEdges struct {
	// Roles holds the value of the roles edge.
	Roles *Role `json:"roles,omitempty"`
	// Menus holds the value of the menus edge.
	Menus *Menu `json:"menus,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// RolesOrErr returns the Roles value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e Role_MenuEdges) RolesOrErr() (*Role, error) {
	if e.Roles != nil {
		return e.Roles, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: role.Label}
	}
	return nil, &NotLoadedError{edge: "roles"}
}

// MenusOrErr returns the Menus value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e Role_MenuEdges) MenusOrErr() (*Menu, error) {
	if e.Menus != nil {
		return e.Menus, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: menu.Label}
	}
	return nil, &NotLoadedError{edge: "menus"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Role_Menu) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case role_menu.FieldCreatedAt, role_menu.FieldUpdatedAt:
			values[i] = new(sql.NullInt64)
		case role_menu.FieldID, role_menu.FieldCreatedBy, role_menu.FieldUpdatedBy, role_menu.FieldRoleID, role_menu.FieldMenuID:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Role_Menu fields.
func (rm *Role_Menu) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case role_menu.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				rm.ID = value.String
			}
		case role_menu.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				rm.CreatedAt = value.Int64
			}
		case role_menu.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				rm.UpdatedAt = value.Int64
			}
		case role_menu.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				rm.CreatedBy = value.String
			}
		case role_menu.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				rm.UpdatedBy = value.String
			}
		case role_menu.FieldRoleID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role_id", values[i])
			} else if value.Valid {
				rm.RoleID = value.String
			}
		case role_menu.FieldMenuID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field menu_id", values[i])
			} else if value.Valid {
				rm.MenuID = value.String
			}
		default:
			rm.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Role_Menu.
// This includes values selected through modifiers, order, etc.
func (rm *Role_Menu) Value(name string) (ent.Value, error) {
	return rm.selectValues.Get(name)
}

// QueryRoles queries the "roles" edge of the Role_Menu entity.
func (rm *Role_Menu) QueryRoles() *RoleQuery {
	return NewRoleMenuClient(rm.config).QueryRoles(rm)
}

// QueryMenus queries the "menus" edge of the Role_Menu entity.
func (rm *Role_Menu) QueryMenus() *MenuQuery {
	return NewRoleMenuClient(rm.config).QueryMenus(rm)
}

// Update returns a builder for updating this Role_Menu.
// Note that you need to call Role_Menu.Unwrap() before calling this method if this Role_Menu
// was returned from a transaction, and the transaction was committed or rolled back.
func (rm *Role_Menu) Update() *RoleMenuUpdateOne {
	return NewRoleMenuClient(rm.config).UpdateOne(rm)
}

// Unwrap unwraps the Role_Menu entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (rm *Role_Menu) Unwrap() *Role_Menu {
	_tx, ok := rm.config.driver.(*txDriver)
	if !ok {
		panic("ent: Role_Menu is not a transactional entity")
	}
	rm.config.driver = _tx.drv
	return rm
}

// String implements the fmt.Stringer.
func (rm *Role_Menu) String() string {
	var builder strings.Builder
	builder.WriteString("Role_Menu(")
	builder.WriteString(fmt.Sprintf("id=%v, ", rm.ID))
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", rm.CreatedAt))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fmt.Sprintf("%v", rm.UpdatedAt))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(rm.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(rm.UpdatedBy)
	builder.WriteString(", ")
	builder.WriteString("role_id=")
	builder.WriteString(rm.RoleID)
	builder.WriteString(", ")
	builder.WriteString("menu_id=")
	builder.WriteString(rm.MenuID)
	builder.WriteByte(')')
	return builder.String()
}

// Role_Menus is a parsable slice of Role_Menu.
type Role_Menus []*Role_Menu
