// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/golden-ocean/fiber-ocean/ent/menu"
	"github.com/golden-ocean/fiber-ocean/ent/predicate"
	"github.com/golden-ocean/fiber-ocean/ent/role"
	"github.com/golden-ocean/fiber-ocean/ent/role_menu"
)

// RoleMenuQuery is the builder for querying Role_Menu entities.
type RoleMenuQuery struct {
	config
	ctx        *QueryContext
	order      []role_menu.OrderOption
	inters     []Interceptor
	predicates []predicate.Role_Menu
	withRoles  *RoleQuery
	withMenus  *MenuQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RoleMenuQuery builder.
func (rmq *RoleMenuQuery) Where(ps ...predicate.Role_Menu) *RoleMenuQuery {
	rmq.predicates = append(rmq.predicates, ps...)
	return rmq
}

// Limit the number of records to be returned by this query.
func (rmq *RoleMenuQuery) Limit(limit int) *RoleMenuQuery {
	rmq.ctx.Limit = &limit
	return rmq
}

// Offset to start from.
func (rmq *RoleMenuQuery) Offset(offset int) *RoleMenuQuery {
	rmq.ctx.Offset = &offset
	return rmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rmq *RoleMenuQuery) Unique(unique bool) *RoleMenuQuery {
	rmq.ctx.Unique = &unique
	return rmq
}

// Order specifies how the records should be ordered.
func (rmq *RoleMenuQuery) Order(o ...role_menu.OrderOption) *RoleMenuQuery {
	rmq.order = append(rmq.order, o...)
	return rmq
}

// QueryRoles chains the current query on the "roles" edge.
func (rmq *RoleMenuQuery) QueryRoles() *RoleQuery {
	query := (&RoleClient{config: rmq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(role_menu.Table, role_menu.FieldID, selector),
			sqlgraph.To(role.Table, role.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, role_menu.RolesTable, role_menu.RolesColumn),
		)
		fromU = sqlgraph.SetNeighbors(rmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMenus chains the current query on the "menus" edge.
func (rmq *RoleMenuQuery) QueryMenus() *MenuQuery {
	query := (&MenuClient{config: rmq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(role_menu.Table, role_menu.FieldID, selector),
			sqlgraph.To(menu.Table, menu.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, role_menu.MenusTable, role_menu.MenusColumn),
		)
		fromU = sqlgraph.SetNeighbors(rmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Role_Menu entity from the query.
// Returns a *NotFoundError when no Role_Menu was found.
func (rmq *RoleMenuQuery) First(ctx context.Context) (*Role_Menu, error) {
	nodes, err := rmq.Limit(1).All(setContextOp(ctx, rmq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{role_menu.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rmq *RoleMenuQuery) FirstX(ctx context.Context) *Role_Menu {
	node, err := rmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Role_Menu ID from the query.
// Returns a *NotFoundError when no Role_Menu ID was found.
func (rmq *RoleMenuQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = rmq.Limit(1).IDs(setContextOp(ctx, rmq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{role_menu.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rmq *RoleMenuQuery) FirstIDX(ctx context.Context) string {
	id, err := rmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Role_Menu entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Role_Menu entity is found.
// Returns a *NotFoundError when no Role_Menu entities are found.
func (rmq *RoleMenuQuery) Only(ctx context.Context) (*Role_Menu, error) {
	nodes, err := rmq.Limit(2).All(setContextOp(ctx, rmq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{role_menu.Label}
	default:
		return nil, &NotSingularError{role_menu.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rmq *RoleMenuQuery) OnlyX(ctx context.Context) *Role_Menu {
	node, err := rmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Role_Menu ID in the query.
// Returns a *NotSingularError when more than one Role_Menu ID is found.
// Returns a *NotFoundError when no entities are found.
func (rmq *RoleMenuQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = rmq.Limit(2).IDs(setContextOp(ctx, rmq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{role_menu.Label}
	default:
		err = &NotSingularError{role_menu.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rmq *RoleMenuQuery) OnlyIDX(ctx context.Context) string {
	id, err := rmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Role_Menus.
func (rmq *RoleMenuQuery) All(ctx context.Context) ([]*Role_Menu, error) {
	ctx = setContextOp(ctx, rmq.ctx, "All")
	if err := rmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Role_Menu, *RoleMenuQuery]()
	return withInterceptors[[]*Role_Menu](ctx, rmq, qr, rmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rmq *RoleMenuQuery) AllX(ctx context.Context) []*Role_Menu {
	nodes, err := rmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Role_Menu IDs.
func (rmq *RoleMenuQuery) IDs(ctx context.Context) (ids []string, err error) {
	if rmq.ctx.Unique == nil && rmq.path != nil {
		rmq.Unique(true)
	}
	ctx = setContextOp(ctx, rmq.ctx, "IDs")
	if err = rmq.Select(role_menu.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rmq *RoleMenuQuery) IDsX(ctx context.Context) []string {
	ids, err := rmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rmq *RoleMenuQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rmq.ctx, "Count")
	if err := rmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rmq, querierCount[*RoleMenuQuery](), rmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rmq *RoleMenuQuery) CountX(ctx context.Context) int {
	count, err := rmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rmq *RoleMenuQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rmq.ctx, "Exist")
	switch _, err := rmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rmq *RoleMenuQuery) ExistX(ctx context.Context) bool {
	exist, err := rmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RoleMenuQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rmq *RoleMenuQuery) Clone() *RoleMenuQuery {
	if rmq == nil {
		return nil
	}
	return &RoleMenuQuery{
		config:     rmq.config,
		ctx:        rmq.ctx.Clone(),
		order:      append([]role_menu.OrderOption{}, rmq.order...),
		inters:     append([]Interceptor{}, rmq.inters...),
		predicates: append([]predicate.Role_Menu{}, rmq.predicates...),
		withRoles:  rmq.withRoles.Clone(),
		withMenus:  rmq.withMenus.Clone(),
		// clone intermediate query.
		sql:  rmq.sql.Clone(),
		path: rmq.path,
	}
}

// WithRoles tells the query-builder to eager-load the nodes that are connected to
// the "roles" edge. The optional arguments are used to configure the query builder of the edge.
func (rmq *RoleMenuQuery) WithRoles(opts ...func(*RoleQuery)) *RoleMenuQuery {
	query := (&RoleClient{config: rmq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rmq.withRoles = query
	return rmq
}

// WithMenus tells the query-builder to eager-load the nodes that are connected to
// the "menus" edge. The optional arguments are used to configure the query builder of the edge.
func (rmq *RoleMenuQuery) WithMenus(opts ...func(*MenuQuery)) *RoleMenuQuery {
	query := (&MenuClient{config: rmq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rmq.withMenus = query
	return rmq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt int64 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RoleMenu.Query().
//		GroupBy(role_menu.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rmq *RoleMenuQuery) GroupBy(field string, fields ...string) *RoleMenuGroupBy {
	rmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RoleMenuGroupBy{build: rmq}
	grbuild.flds = &rmq.ctx.Fields
	grbuild.label = role_menu.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt int64 `json:"created_at,omitempty"`
//	}
//
//	client.RoleMenu.Query().
//		Select(role_menu.FieldCreatedAt).
//		Scan(ctx, &v)
func (rmq *RoleMenuQuery) Select(fields ...string) *RoleMenuSelect {
	rmq.ctx.Fields = append(rmq.ctx.Fields, fields...)
	sbuild := &RoleMenuSelect{RoleMenuQuery: rmq}
	sbuild.label = role_menu.Label
	sbuild.flds, sbuild.scan = &rmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RoleMenuSelect configured with the given aggregations.
func (rmq *RoleMenuQuery) Aggregate(fns ...AggregateFunc) *RoleMenuSelect {
	return rmq.Select().Aggregate(fns...)
}

func (rmq *RoleMenuQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rmq); err != nil {
				return err
			}
		}
	}
	for _, f := range rmq.ctx.Fields {
		if !role_menu.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rmq.path != nil {
		prev, err := rmq.path(ctx)
		if err != nil {
			return err
		}
		rmq.sql = prev
	}
	return nil
}

func (rmq *RoleMenuQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Role_Menu, error) {
	var (
		nodes       = []*Role_Menu{}
		_spec       = rmq.querySpec()
		loadedTypes = [2]bool{
			rmq.withRoles != nil,
			rmq.withMenus != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Role_Menu).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Role_Menu{config: rmq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rmq.withRoles; query != nil {
		if err := rmq.loadRoles(ctx, query, nodes, nil,
			func(n *Role_Menu, e *Role) { n.Edges.Roles = e }); err != nil {
			return nil, err
		}
	}
	if query := rmq.withMenus; query != nil {
		if err := rmq.loadMenus(ctx, query, nodes, nil,
			func(n *Role_Menu, e *Menu) { n.Edges.Menus = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rmq *RoleMenuQuery) loadRoles(ctx context.Context, query *RoleQuery, nodes []*Role_Menu, init func(*Role_Menu), assign func(*Role_Menu, *Role)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Role_Menu)
	for i := range nodes {
		fk := nodes[i].RoleID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(role.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "role_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (rmq *RoleMenuQuery) loadMenus(ctx context.Context, query *MenuQuery, nodes []*Role_Menu, init func(*Role_Menu), assign func(*Role_Menu, *Menu)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Role_Menu)
	for i := range nodes {
		fk := nodes[i].MenuID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(menu.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "menu_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (rmq *RoleMenuQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rmq.querySpec()
	_spec.Node.Columns = rmq.ctx.Fields
	if len(rmq.ctx.Fields) > 0 {
		_spec.Unique = rmq.ctx.Unique != nil && *rmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rmq.driver, _spec)
}

func (rmq *RoleMenuQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(role_menu.Table, role_menu.Columns, sqlgraph.NewFieldSpec(role_menu.FieldID, field.TypeString))
	_spec.From = rmq.sql
	if unique := rmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rmq.path != nil {
		_spec.Unique = true
	}
	if fields := rmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, role_menu.FieldID)
		for i := range fields {
			if fields[i] != role_menu.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if rmq.withRoles != nil {
			_spec.Node.AddColumnOnce(role_menu.FieldRoleID)
		}
		if rmq.withMenus != nil {
			_spec.Node.AddColumnOnce(role_menu.FieldMenuID)
		}
	}
	if ps := rmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rmq *RoleMenuQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rmq.driver.Dialect())
	t1 := builder.Table(role_menu.Table)
	columns := rmq.ctx.Fields
	if len(columns) == 0 {
		columns = role_menu.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rmq.sql != nil {
		selector = rmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rmq.ctx.Unique != nil && *rmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rmq.predicates {
		p(selector)
	}
	for _, p := range rmq.order {
		p(selector)
	}
	if offset := rmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RoleMenuGroupBy is the group-by builder for Role_Menu entities.
type RoleMenuGroupBy struct {
	selector
	build *RoleMenuQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rmgb *RoleMenuGroupBy) Aggregate(fns ...AggregateFunc) *RoleMenuGroupBy {
	rmgb.fns = append(rmgb.fns, fns...)
	return rmgb
}

// Scan applies the selector query and scans the result into the given value.
func (rmgb *RoleMenuGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rmgb.build.ctx, "GroupBy")
	if err := rmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RoleMenuQuery, *RoleMenuGroupBy](ctx, rmgb.build, rmgb, rmgb.build.inters, v)
}

func (rmgb *RoleMenuGroupBy) sqlScan(ctx context.Context, root *RoleMenuQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rmgb.fns))
	for _, fn := range rmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rmgb.flds)+len(rmgb.fns))
		for _, f := range *rmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RoleMenuSelect is the builder for selecting fields of RoleMenu entities.
type RoleMenuSelect struct {
	*RoleMenuQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rms *RoleMenuSelect) Aggregate(fns ...AggregateFunc) *RoleMenuSelect {
	rms.fns = append(rms.fns, fns...)
	return rms
}

// Scan applies the selector query and scans the result into the given value.
func (rms *RoleMenuSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rms.ctx, "Select")
	if err := rms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RoleMenuQuery, *RoleMenuSelect](ctx, rms.RoleMenuQuery, rms, rms.inters, v)
}

func (rms *RoleMenuSelect) sqlScan(ctx context.Context, root *RoleMenuQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rms.fns))
	for _, fn := range rms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
